### ISSUE TITLE
PID for STM32

### ISSUE THREAD

**Issue by ebimicro** [Majid-Derhambakhsh/PID-Library#2]
Dear, thanks for the great job but would you please share your STM32 code as well? because I tried your code in AtolicTrueStudio and I get so many issue regarding TypeDef etc. And also it's not clear how new temperature reading will be taken in count for PID calculation. Thanks in advance.

**Comment by Majid-Derhambakhsh** [comment]
Thanks for your feedback, the STM32 sample will be uploaded soon.

**Comment by ebimicro** [comment]
Thanks @Majid-Derhambakhsh , to be honest I already use a STM PID library and it works fine generally but still interested in solutions with more options to config. Looking forward to see the codes samples are uploaded  ;-)

**Comment by Majid-Derhambakhsh** [comment]
@ebimicro 

An example was uploaded, remember in this example temperature has simulated by ratios.
You can view the parameters in the serial monitor with '115200' Baud Rate.

**Comment by ebimicro** [comment]
@Majid-Derhambakhsh 
Great, thank you again, I downloaded the project, will try it out asap. Great job ;-)
