### ISSUE TITLE
Substracting Derivative 

### ISSUE THREAD

**Issue by Slaih** [Majid-Derhambakhsh/PID-Library#3]
Why did you do output equation like this:  output += uPID->OutputSum - uPID->Kd * dInput;

I think that uPID->Kd * dInput value should be added to output instead of substracted.

**Comment by Majid-Derhambakhsh** [comment]
Hi, because we need to add a fraction of the remainder of the output to the output.

this library is based on the Arduino library

**Comment by Slaih** [comment]
I did not understand. In control, I know that derivative of the error should be added to total output but you calculate derivat,ve of the input and substracting it. Am I missing something?

**Comment by BilalAzhar0** [comment]
I think it is to prevent sudden kicks during set point changes.
https://youtu.be/zOByx3Izf5U
8:45 minutes

**Comment by Slaih** [comment]
> I think it is to prevent sudden kicks during set point changes.
> https://youtu.be/zOByx3Izf5U
> 8:45 minutes 

I understand that while getting closer to setpoint, derivative of error will be negative and derivative of input will be positive. Because of this it is multiplied with -1.
