### ISSUE TITLE
Multiple PIDs in C

### ISSUE THREAD

**Issue by raulperez** [Majid-Derhambakhsh/PID-Library#4]
Hi

Is it possible to use multiple PIDs with the C version?

Best regards

**Comment by Majid-Derhambakhsh** [comment]
> Hi
> 
> Is it possible to use multiple PIDs with the C version?
> 
> Best regards

Hi

Yes, you can use multiple PID controllers in your c program. the data structure is stored in PID_TypeDef type.

Good luck.
